os: linux
dist: bionic

language: go

go:
  - 1.14.x

go_import_path: github.com/mdblp/gatekeeper

env:
  global:
    - GO111MODULE=on
    - BUILD_OPENAPI_DOC=true
    - BUILD_SOUP=true

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  - provider: s3
    on:
      tags: true
    # You can refer to environment variables from Travis repo settings!
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    # Name of the S3 bucket to which your site should be uploaded.
    bucket: $AWS_BUCKET
    # Prevent Travis from deleting your built site so it can be uploaded.
    cleanup: false
    # Path of the source directory containing your built site.
    local_dir: deploy
    # Path to a directory containing your built site.
    upload_dir: deploy
    # Set the Cache-Control header.
    cache_control: "max-age=21600"
  # Deploy doc
  - provider: s3
    on:
      tags: true
    # You can refer to environment variables from Travis repo settings!
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    # Name of the S3 bucket to which your site should be uploaded.
    bucket: com.diabeloop.yourloops.doc
    # Prevent Travis from deleting your built site so it can be uploaded.
    cleanup: false
    # Path of the source directory containing your built site.
    local_dir: doc/openapi
    # Path to a directory containing your built site.
    upload_dir: openapi/gatekeeper
    # Set the Cache-Control header.
    cache_control: "max-age=21600"
  # Deploy SOUP list
  - provider: s3
    on:
      tags: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: com.diabeloop.yourloops.doc
    cleanup: false
    local_dir: doc/soup
    upload_dir: soup/gatekeeper
    cache_control: "max-age=21600"

services:
  - docker

script:
  - go install github.com/swaggo/swag/cmd/swag
  - make
  - make test
  - make docker
