export PORT='9123'
export SERVER_SECRET='This needs to be the same secret everywhere. YaHut75NsK1f9UKUXuWqxNN0RUwHFBCy'
export GATEKEEPER_SECRET='This secret is used to encrypt the groupId stored in the DB for gatekeeper'
export SHORELINE_SECRET='This is a local API secret for everyone. BsscSHqSHiwrBMJsEGqbvXiuIUPAjQXU'
export PORTAL_API_HOST='http://localhost:9507'
export SHORELINE_HOST='http://localhost:9107'
export PORTAL_API_HOST='http://localhost:9507'
export SKIP_HAKKEN='true'
